[plugins]
jsonnet = "https://github.com/Banno/asdf-jsonnet.git"

[tools]
awscli = "latest"
aws-sam-cli = "latest"
aws-vault = "latest"
gcloud = "latest"
bat = "latest"
buildpack = "latest"
bun = "latest"
chezmoi = "latest"
delta = "latest"
deno = "latest"
duf = "latest"
editorconfig-checker = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
go = "latest"
gomigrate = "latest"
jq = "latest"
jsonnet = "latest"
mkcert = "latest"
node = "lts"
php = ["8.0", "8.1", "8.2"]
protoc = "latest"
racket = "latest"
ripgrep = "latest"
ruby = "2.3.8"
rust = "latest"
rye = "latest"
sqlite = "latest"
terraform = "latest"
yq = "latest"

[settings]
legacy_version_file = true
legacy_version_file_disable_tools = ["python"]

plugin_autoupdate_last_check_duration = "1 week"

verbose = false
asdf_compat = false
http_timeout = "30s"
jobs = 4
raw = false
yes = false

[env]

MISE_FETCH_REMOTE_VERSIONS_TIMEOUT = "120 sec"
