[tools]
"aqua:kayac/ecspresso" = "latest"
"aqua:fujiwara/lambroll" = "latest"
"aqua:suzuki-shunsuke/pinact" = "latest"
"asdf:Banno/asdf-jsonnet" = "latest"
aws-vault = "latest"
awscli = "latest"
bat = "latest"
buildpack = "latest"
bun = "latest"
"cargo:viu" = "latest"
delta = "latest"
duckdb = "latest"
duf = "latest"
editorconfig-checker = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
ghq = "latest"
github-cli = "latest"
go = "latest"
gomigrate = "latest"
"go:golang.org/x/tools/gopls" = "latest"
jj = "latest"
jq = "latest"
mkcert = "latest"
node = ["20", "lts"]
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"npm:@ralph-orchestrator/ralph-cli" = "latest"
"npm:agent-browser" = "latest"
"npm:ccusage" = "latest"
"npm:intelephense" = "latest"
"npm:jsdoc-to-markdown" = "latest"
"npm:madge" = "latest"
"npm:opencommit" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
php = ["8.2"]
protoc = "latest"
python = ["3.12"]
racket = ["9.0"]
ripgrep = "latest"
rust = "latest"
rye = "latest"
sqlite = "latest"
terraform = "latest"
uv = "latest"
yq = "latest"

[settings]
legacy_version_file = true
legacy_version_file_disable_tools = ["python"]

plugin_autoupdate_last_check_duration = "1 week"

verbose = false
asdf_compat = false
http_timeout = "30s"
jobs = 4
raw = false
yes = false
idiomatic_version_file_enable_tools = ["go"]
experimental = true

[settings.npm]
bun = true

[env]
MISE_FETCH_REMOTE_VERSIONS_TIMEOUT = "120 sec"

[tasks.claude_serena]
description = "Add Serena MCP to Claude Code"
run = "claude mcp add serena -- uvx --from git+https://github.com/oraios/serena serena start-mcp-server --context ide-assistant --project $(pwd)"

[tasks.serena_index]
description = "Serena activation & indexing project"
run = "uvx --from git+https://github.com/oraios/serena serena project index"
