[alias]
jsonnet = "asdf:Banno/asdf-jsonnet"

[tools]
awscli = "latest"
aws-sam-cli = "latest"
aws-vault = "latest"
gcloud = "latest"
bat = "latest"
buildpack = "latest"
bun = "latest"
# chezmoi = "latest"
delta = "latest"
deno = "latest"
duf = "latest"
editorconfig-checker = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
go = "latest"
gomigrate = "latest"
jq = "latest"
jsonnet = "latest"
mkcert = "latest"
node = ["20", "lts", "latest"]
php = ["8.2"]
protoc = "latest"
python = ["3.12"]
uv = "latest"
#racket = "latest"
ripgrep = "latest"
#ruby = "2.3.8"
rust = "latest"
rye = "latest"
sqlite = "latest"
terraform = "latest"
yq = "latest"
duckdb = "latest"
"aqua:fujiwara/lambroll" = "latest"
"aqua:kayac/ecspresso" = "latest"
"aqua:suzuki-shunsuke/pinact" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:ccusage" = "latest"
"npm:opencommit" = "latest"
"npm:@openai/codex" = "latest"


[settings]
legacy_version_file = true
legacy_version_file_disable_tools = ["python"]

plugin_autoupdate_last_check_duration = "1 week"

verbose = false
asdf_compat = false
http_timeout = "30s"
jobs = 4
raw = false
yes = false
idiomatic_version_file_enable_tools = ["go"]
experimental = true

[settings.npm]
bun = true

[env]
MISE_FETCH_REMOTE_VERSIONS_TIMEOUT = "120 sec"

[tasks.claude_serena]
description = "Add Serena MCP to Claude Code"
run = "claude mcp add serena -- uvx --from git+https://github.com/oraios/serena serena start-mcp-server --context ide-assistant --project $(pwd)"

[tasks.serena_index]
description = "Serena activation & indexing project"
run = "uvx --from git+https://github.com/oraios/serena serena project index"

