[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']
hook_source = '''
  call ddc#custom#patch_global('sources', ['nvim-lsp', 'around'])
  call ddc#custom#patch_global('sourceOptions', {
        \ '_': {
        \   'matchers': ['matcher_head'],
        \   'sorters': ['sorter_rank']},
        \ 'around': {
        \   'mark': 'around' },
        \ 'nvim-lsp': {
        \   'mark': 'lsp',
        \   'forceCompletionPattern': '\.\w*|:\w*|->\w*' },
        \ })
  call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'
hook_source = '''
  call ddc#custom#patch_global('ui', 'native')
'''

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

#
# general
#
[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
hook_source = '''
  let g:prettier#autoformat = 0
  let g:prettier#quickfix_enabled = 0
  autocmd BufWritePre *.js,*.ts,*.vue,*.css,*.scss,*.json,*.md PrettierAsync
'''

#
# javascript
#
[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'javascript.jsx', 'ts', 'typescript']

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
    let g:vim_json_syntax_conceal = 0
'''
on_ft = ['javascript', 'javascript.jsx', 'json']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['jsx', 'javascript.jsx']
hook_add = '''
  let g:jsx_ext_required = 1
'''

#
# typescript
#
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts', 'typescript']
hook_add = '''
'''

#
# html
#
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
    let g:user_emmet_install_global = 1
    let g:user_emmet_leader_key='<C-y>'
'''
on_ft = ['html', 'vue', 'tag', 'txt', 'text', 'eruby']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css', 'scss', 'less']

[[plugins]]
repo = 'othree/html5.vim'
hook_add = '''
    au BufRead,BufNewFile,BufReadPre *.ejs set filetype=html
'''
on_ft = ['html', 'vue', 'tag', 'txt', 'text']

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['html', 'vue', 'tag', 'txt', 'text', 'css', 'scss', 'less', 'slim', 'erb']

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'vue', 'tag', 'txt', 'text', 'css', 'scss', 'less', 'slim', 'erb']

#
# markdown
#
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_conceal = 0
  let g:vim_markdown_conceal_code_blocks = 0
  autocmd BufRead,BufNewFile *.mkd set filetype=markdown
  autocmd BufRead,BufNewFile *.md set filetype=markdown
'''
on_ft = ['markdown', 'mkd', 'md']


[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'mkd', 'md']

#
# reStructuredText
#
[[plugins]]
repo = 'vim-scripts/rest.vim'
on_ft = ['rest']


[[plugins]]
repo = 'mattn/vim-goimports'
hook_add = '''
  let g:goimports_simplify = 1
'''
on_ft = ['go']

#
# SICP
#
[[plugins]]
repo = 'olical/conjure'
on_ft = ['racket']

[[plugins]]
repo = 'wlangstroth/vim-racket'
on_ft = ['racket']

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'
on_ft = ['racket']
hook_add = '''
  let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
  let g:rbpt_max = 16
  let g:rbpt_loadcmd_toggle = 0
'''

