[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['Shougo/unite.vim']

[[plugins]]
repo      = 'Shougo/neoyank.vim'
on_source = ['Shougo/unite.vim']

[[plugins]]
repo      = 'kmnk/vim-unite-giti'
on_source = ['Shougo/unite.vim']

[[plugins]]
repo      = 'ujihisa/unite-colorscheme'
on_source = ['Shougo/unite.vim']

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'junegunn/vim-emoji'

[[plugins]]
repo    = 'rhysd/github-complete.vim'
depends = ['Shougo/vimproc.vim', 'Shougo/vimproc.vim', 'junegunn/vim-emoji']

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo    = 'shumphrey/fugitive-gitlab.vim'
depends = ['tpope/vim-fugitive']

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Align'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
