[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['Shougo/unite.vim']

[[plugins]]
repo      = 'Shougo/neoyank.vim'
on_source = ['Shougo/unite.vim']

[[plugins]]
repo      = 'kmnk/vim-unite-giti'
on_source = ['Shougo/unite.vim']

[[plugins]]
repo      = 'ujihisa/unite-colorscheme'
on_source = ['Shougo/unite.vim']

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'junegunn/vim-emoji'

[[plugins]]
repo    = 'rhysd/github-complete.vim'
depends = ['Shougo/vimproc.vim', 'Shougo/vimproc.vim', 'junegunn/vim-emoji']

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo    = 'shumphrey/fugitive-gitlab.vim'
depends = ['tpope/vim-fugitive']

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'powerman/vim-plugin-AnsiEsc'

[[plugins]]
repo = 'thinca/vim-quickrun'
